### ISSUE TITLE
Negative stock.

### ISSUE THREAD

**Issue by DodoVoelkel** [samnabi/shopkit#130]
A client of mine whom is using shopkit said to me that a product variant went from "Sold out" a couple of days to buyable again.
When they looked in the panel the variant had a stock of "-13".
How could that possibly happen?

**Comment by invasoria** [comment]
This can happen on multiple scenarios, but the most probable would be one with multiple customers buying the same item with multiple quantities.

For example: If we currently have 10 items in stock for a product and two different users add 10 items to cart each and finish the transaction, at almost the same time, the stock will now be "-10".

This also happens if a store manager changes the stock while a customer is buying something. If a customer adds 10 items to cart from a current stock of 10 and the manager changes the stock to 5, the completed transaction will result in a stock of "-5".

Also, a user can opt to "Pay Later", skip confirmation or return to cart and "buy" the same amount of items again, thus subtracting (or adding) to the negative value.

Possible solutions for this bug? Maybe Shopkit should check the current stock and if negative values exist in before checkout/paying?

**Comment by samnabi** [comment]
The `updateStock()` function, defined in `site/plugins/shopkit.php`, is what modifies your variant's `stock` value.

`updateStock()` is called from `order.callback.php`, which in turn is called from the Payment gateway's `callback.php` file.

When someone returns to your site after paying, they trigger `updateStock()`.

`updateStock()` doesn't check for negative values, it just keeps subtracting.

There are two possible causes:

1. Multiple people are buying items at the same time, like @invasoria mentioned
2. Someone keeps refreshing the page after they return from paying? Not sure exactly how this would work

I see two fixes that need to happen:

1. Right now, `updateStock()` doesn't check for negative values. It should stop at zero.
2. Template code should display "Out of stock" when stock is 0 or less, not just when stock is 0

**Comment by DodoVoelkel** [comment]
Thanks for looking into it. I will post something if i find a solution.

I whould have also assumed the first mentioned cause.
The strange thing is that the item was out of stock for 4 days, and then suddenly became availible again.

**Comment by DodoVoelkel** [comment]
A temporary fix whould be to change the '=== 0' to '<= 0' in line 107 of shopkit.php.
Or is there a specific reason to use === ?

**Comment by samnabi** [comment]
The `===` is necessary to distinguish `0` from an empty field. Remember, if the field is empty, that means unlimited stock.

So you would have to add another test, something like `is_numeric($stock) and $stock <= 0`

**Comment by samnabi** [comment]
This will be fixed in the next version (both 1.x and 2.x branches). I tightened up the logic in both `inStock()` and `updateStock()` function.
