### ISSUE TITLE
captcha

### ISSUE THREAD

**Issue by enginmurat** [samnabi/shopkit#153]
captcha feature for registration spams

**Comment by samnabi** [comment]
The registration page already includes a spam-prevention measure, using the [Honeypot Technique](http://www.dexmedia.com/blog/honeypot-technique/).

See line 21 of the template: https://github.com/samnabi/shopkit/blob/master/site/plugins/shopkit/templates/register.php#L21

Unfortunately CAPTCHAs are difficult to bundle with a software package like Shopkit, because you need to reply on a third-party service. I will not be supporting this feature.
