### ISSUE TITLE
New themes

### ISSUE THREAD

**Issue by enginmurat** [samnabi/shopkit#164]
new templates for shopkit

**Comment by samnabi** [comment]
I'm not sure multiple templates make sense, when all of the Shopkit sites I've seen include heavy customizations of their own.

I will keep this issue open to hear other perspectives.

**Comment by TimOetting** [comment]
I think it would be very useful to have a template that is as minimalistic as possible. Meaning, no styling, no classes, as few javascript and html elements as possible. This would give me a better starting point for a fully customized shop.

**Comment by samnabi** [comment]
@TimOetting what would you like to see built into the 'minimalistic' theme? Some things I might keep in:

- Animated dropdown menus for login form and category menu
- basic layout for product/category cards
- AJAX cart updating
- Basic layout for orders table
- Basic layout for gallery
- Basic layout for slideshow view

Or would you rather implement all of these layouts yourself?

**Comment by TimOetting** [comment]
@samnabi thanks for the reply on this.

I think I would like to just have a simple html frame around all the unique kirby fields that come with shopkit. If that is what you mean by a 'basic layout' I would be happy to see it inside the template. 
I would leave out all the css stuff because that would require to add classes. There are nowadays so many ways to name css classes, I would just keep it open to the developer to decide how to structure the css by simply leaving it away completely. If you want to describe content blocks inside the template I would prefer HTML comments.
I am not sure if I would keep the AJAX cart update functionality in the basic theme. But I think a template that works completely without js would be a preferable solution. It would be nice if there would be a nicely documented API for all those actions that could be utilized by the developers themself if needed.
For orders, gallery and slideshow I would stick with a simple `ul` html list. If there are developers that want to create a theme for shopkit they most likely want to implement their own solution for this kind of content.

Thanks
Tim

**Comment by samnabi** [comment]
Hm, in this case we will still need to change markup (if people are adding their own classes, etc.)

Here's what I propose:

I'll maintain a separate repository with a set of template overrides. These overrides can be dropped in to the `site/` folder. They will have very little formatting, and no javascript.

This will function much in the same way as the [`shopkit-sample-content`](https://github.com/samnabi/shopkit-sample-content) repository.

This means I'll have to maintain two separate sets of templates, and I'll move as much logic as possible into controllers.

I'll also make the snippets as theme-agnostic as possible.

**Comment by enginmurat** [comment]
Hello dear
When will you do it new theme ?

**Comment by enginmurat** [comment]
i suggestion responsive grid and clean design...

**Comment by enginmurat** [comment]
https://victorthemes.com/themes/seese/product-category/decoration/

i suggest similar this design...

**Comment by samnabi** [comment]
I've decided not to maintain a separate repository with another theme, mainly due to time constraints.
