### ISSUE TITLE
Customer account edition

### ISSUE THREAD

**Issue by luclucluc** [samnabi/shopkit#201]
Hi Sam,
When connected with a Customer account it's impossible to access the panel editing page. It just log out.
The link looks ok. Orders page works fine.
Am I missing something?
Using V2.3 with Kirby 2.5.7

Thanks, Luc

**Comment by samnabi** [comment]
Customers cannot access the Panel.

If they could, then they'd be able to edit product prices and order details!

Customers can only access the frontend pages, with the exception of editing their own account details (e.g. password)

**Comment by luclucluc** [comment]
Thanks for your reply, I will be more precise :
My point is that Customers can't access their account details (password, email etc).
The link is " .../panel/users/user-name/edit" and when trying to follow it we are just send back to home page and logged out.

I haven't this issue when using v1.1.6 of Shopkit (witch also use Panel for customers details...).

You can have a look here : http://borho.studio/font/ (customer@customer.com / pass: customer)
Some pages haven't been styled yet but I have the same issue on freshly installed version.

Thanks

**Comment by V0IDNIL** [comment]
I am trying to set up shopkit for the first time and have what seems to be the same issue. 
I have a fresh, unmodified (except for basic shop information) installation of shopkit. When I try to create a test customer and go to the link from the activation mail, I am being redirected to /#login . By manually using the token as a password, I can log in. But if I click on the topmost "My account" button, same thing happens. Instead of going to /panel/users/**username**/edit I just end up at /#login

Is there some setting that I overlooked? Do you have an idea why that happens?
