### ISSUE TITLE
Shipping fails to use shipping method.

### ISSUE THREAD

**Issue by drewreece** [samnabi/shopkit#34]
When adding an item to the cart the shipping fails to apply. 

I have 2 shipping methods setup with 'All countries' & the United Kingdom active.  The popup only ever offers 'Free shipping' when the United Kingdom or any other region is selected. It seems to be the same for logged out users as well as logged in ones.

I have cloned the shopkit repo as described at http://shopkit.samnabi.com, the kirby panel and toolkit are at version 2.2.3.

This is the shipping contents of shopkit/content/2-shop/shop-en.txt…

```
Shipping: 

- 
  method: ground
  flat: "5"
  item: "5"
  weight: |
    0 : 10.11
    20 : 58.00
  price: |
    0.00 : 4.00
    10.00 : 6.00
    30.00 : 18.00
  calculation: high
  countries: all-countries, united-kingdom
- 
  method: test
  countries: >
    all-countries, afghanistan,
    aland-islands
  flat: "2"
  item: "2"
  weight: ""
  price: ""
  calculation: high

```

If I edit shopkit/site/plugins/shopkit/Cart.php and print the shipping methods on line 240 I get an array of the defined methods…

```
print_r($method);
```

but the next line fails to continue on to create the options list…

```
if (!$this->appliesToCountry($method)) continue;
```

It seems that this logic is backwards - is that correct? Should it be without the (!) e.g.

```
if ($this->appliesToCountry($method)) continue;
```

That seems to make it work for me.

**Comment by samnabi** [comment]
Thanks for catching this. I've just pushed a hotfix, and I will issue a new release soon.

The issue is not with line 240 (`continue` skips over that iteration of the loop, so we want to skip methods that **don't** apply to the country).

Instead, the `appliesToCountry()` function had a bug. Its code hadn't been updated to deal with the new version of the Multiselect plugin.

You can pull the fixed version by doing `git clone --recursive https://github.com/samnabi/shopkit.git` from your terminal.
