### ISSUE TITLE
Checkout redirects to 404 error page on subdirectory install 

### ISSUE THREAD

**Issue by aguynamedirvin** [samnabi/shopkit#57]
When I try to checkout a product I get redirected from localhost:8888/shopkit-dev/shop/cart to localhost:8888/shop/cart/process giving me a 404 error. Notice how it seems to not read that it's in a subdirectory. 

I have the latest Shopkit from the dev branch setup in a local dev environment using MAMP under a subdirectory. I have set up the correct url/directory in the config file but it still doesn't seem to be working.

Edit: 
I uploaded it to a live server on a subdirectory to see if it made any difference but it's doing the same thing.

**Comment by samnabi** [comment]
Ah, I thought I had fixed all the hardcoded paths to permit subdirectory installs, but it looks like I forgot a couple lines in `templates/cart.php`.

This will be fixed in the next release. For now, replace the following on lines [159](https://github.com/samnabi/shopkit/blob/master/site/templates/cart.php#L159) and [194](https://github.com/samnabi/shopkit/blob/master/site/templates/cart.php#L159) of `site/templates/cart.php`:

Remove
`<form method="post" action="/shop/cart/process">`

Replace
`<form method="post" action="<?php echo url('shop/cart/process') ?>">`

**Comment by samnabi** [comment]
This has been pushed to the `dev` branch and will be fixed in the 1.1 release.
